video/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.posts , name = 'posts'),
    path('posts/<slug:slug>/', views.post_detail , name = 'post_detail_url'),
    path('category/<slug:slug>/', views.category_detail , name = 'category_detail_url'),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.login_site, name='login_site'),
    path('logout/', views.logout_site, name='logout_site'),
    path('post_detail/<slug:slug>/comment/', views.comment, name='comment'),
    path('search/', views.search, name='search'),
    path('profile/<slug:user_id>/', views.profile, name = 'profile'),
    path('create_post/', views.create_post, name = 'create_post'),
    path('post_delete/<slug:slug>', views.post_delete, name = 'post_delete'),
    path('edit_post/<slug:slug>', views.edit_post, name = 'edit_post'),   
    path('posts/<slug:slug>/like/', views.like, name = 'like'),
]

video_blog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class Post(models.Model):
    author =  models.ForeignKey(User, on_delete=models.CASCADE, null = True , blank = True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    preview = models.ImageField(upload_to = 'post_previews/')
    video = models.FileField(upload_to='post_videos/')
    date = models.DateTimeField(default = timezone.now)
    published = models.BooleanField(default = False)
    category = models.ManyToManyField('Category')
    featured = models.BooleanField(default= False)
    slug = models.SlugField(unique = True)

    class  Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'

    def __str__(self):
        return self.title
    
    def get_link(self):
        return reverse('post_detail_url', kwargs= {'slug': self.slug})
    
class Category(models.Model):
    title = models.CharField(max_length = 255)
    slug = models.SlugField(unique = True)

    class Meta:
        verbose_name = 'Категория'  
        verbose_name_plural = 'Категории'
        
    def __str__(self):
        return self.title

    def get_link(self):
        return reverse('category_detail_url', kwargs= {'slug': self.slug})
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    avatar = models.ImageField(upload_to= 'user_avatars/', null= True)
    banner = models.ImageField(upload_to='user_banners/', null= True)
    birth_day = models.DateField(null = True)
    description = models.TextField(null= True, blank= True)

    class Meta:
        verbose_name = 'Профиль'  
        verbose_name_plural = 'Профили'
        
    def __str__(self):
        return self.user.username

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(default = timezone.now)

    class Meta:
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'

    def __str__(self):
        return self.author.username + self.text
    
class View(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, null= True, blank=True)
    date = models.DateTimeField(default= timezone.now)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, null= True, blank=True)
    date = models.DateTimeField(default= timezone.now)
    
    

        




        

video/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Логин', required= True , widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Логин"}))
    password1= forms.CharField(label='Пароль', required= True , widget=forms.PasswordInput(attrs={'class': 'form-control mb-3', 'placeholder':"Пароль"}))
    password2 = forms.CharField(label='Подтверждение пароля', required= True , widget=forms.PasswordInput(attrs={'class': 'form-control mb-3', 'placeholder':"Подтверждение пароля"}))
    email = forms.EmailField(label='Почта', required= True , widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Почта"}))
    first_name = forms.CharField(label='Имя', required= False , widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Имя"}))
    last_name = forms.CharField(label='Логин', required= False , widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Фамилия"}))
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
            return user

video/views.py
from django.shortcuts import render ,  redirect
from .models import Post , Category , Profile , Comment , Like , View
from django.core.paginator import Paginator , PageNotAnInteger , EmptyPage
from django.contrib.auth import authenticate , login , logout
from django.urls import reverse
from .forms import RegisterForm
from .translit import translit
from random import randint
from django.utils import timezone
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
 

def index(request):
    posts = Post.objects.filter(published=True).order_by('-date')[:9]
    featureds = Post.objects.filter(featured = True).order_by('-date')[:5]
    categories = Category.objects.all()
    context = {'posts' : posts, 'featureds' : featureds, 'categories' : categories}
    return render(request, 'index.html', context)

def posts(request):
    categories = Category.objects.all()
    posts = Post.objects.filter(published=True).order_by('-date')[:9]
    paginator = Paginator(posts, 20)
    page = request.GET.get('page')
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = paginator.get_page(1)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    posts = paginator.get_page(page)
    context = {'posts' : posts, 'categories' : categories}
    return render(request, 'posts.html')

def post_detail(request, slug):
    post = Post.objects.get(slug__exact=slug)
    if request.user.is_authenticated:
        if not post.view_set.filter(user = request.user).exists():
            post.view_set.create(user = request.user)
        else:
            view = request.user.view_set.get(post=post)
            view.date = timezone.now()
            view.save()    
    return render(request, 'post_detail.html', {'post': post})

def category_detail(request, slug):
    category = Category.objects.get(slug__exact = slug)
    return render(request, 'category_detail.html', {'category':category})

def login_site(request):
    if request.user.is_authenticated:
        return redirect('index')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            message = 'Username or password in incorrect'
            return render(request, 'login.html', {'message': message})
    return render(request, 'login.html')

def logout_site(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('index')

def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                user = form.save()
                profile = Profile()
                profile.user = user 
                profile.save()
                login(request, user)
                return redirect('index')
        else:
            form = RegisterForm()
        return render(request, 'register.html', {'form':form})
    return redirect('index')        
    
def comment(request,slug):
    post = Post.objects.get(slug__exact=slug)
    if request.method == 'POST':
        comment = Comment()
        comment.author = request.user
        comment.post = post
        comment.text = request.POST.get('text')
        if not comment.text:
             return redirect(reverse('post_detail_url', kwargs={'slug': slug}))
        comment.save()
        return redirect(reverse('post_detail_url', kwargs ={'slug': slug}))
    return redirect(reverse('post_detail_url', kwargs ={'slug': post.slug}))

def create_post(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        post = Post()
        post.title = request.POST.get('title')
        post.author = request.user
        new_slug = translit(request.POST.get('title'))
        if Post.objects.filter(slug__exact = new_slug).exists():
            post.slug = new_slug + '' + str(timezone.now().format('Y-m-d_H-i-s')) + '' + str(randint(1,100))
        else:
            post.slug = new_slug
        if request.FILES.get('preview', False) != False:
            myimage = request.FILES['preview']
            fsi = FileSystemStorage()
            filenameimage = fsi.save(myimage.name, myimage)
            post.preview = filenameimage
        if request.FILES.get('video', False) != False:
            myvideo = request.FILES['video']
            fsv = FileSystemStorage()
            filenamevideo = fsv.save(myvideo.name, myvideo)
            post.video = filenamevideo
        post.description = request.POST.get('description')
        post.save()
        category_ids = request.POST.getlist('categories[]')
        for id in category_ids:
            post.category.add(id)
        return redirect('index')
    return render(request, 'create_post.html', {'categories': categories })


#  <----Поиск---->
def search(request):
    query = request.GET.get('search')
    posts = Post.objects.filter(Q(title__iregex = query))
    content = {'posts': posts, 'query' : query }
    return render(request, 'search.html', content)

def profile(request, user_id):
    profile = Profile.objects.get(user_id__exact = request.user.id)
    return render(request, "profile.html", {'profile': profile})

def post_delete(request, slug):
    post = Post.objects.get(slug__exact=slug)
    post.delete()
    return redirect('index')    

    
def edit_post(request, slug):
    categories = Category.objects.all()
    post = Post.objects.get(slug__exact=slug)
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.author = request.user
        new_slug = translit(request.POST.get('title'))
        post.slug = new_slug
        if request.FILES.get('preview', False) != False:
            myimage = request.FILES['preview']
            fsi = FileSystemStorage()
            filenameimage = fsi.save(myimage.name, myimage)
            post.preview = filenameimage
        if request.FILES.get('video', False) != False:
            myvideo = request.FILES['video']
            fsv = FileSystemStorage()
            filenamevideo = fsv.save(myvideo.name, myvideo)
            post.video = filenamevideo
        post.description = request.POST.get('description')
        post.save()
        category_ids = request.POST.getlist('categories[]')
        for id in category_ids:
            post.category.add(id)
        return redirect('index')
    return render(request, 'edit_post.html', {'categories': categories,'post':post })

def like(request, slug):
    post = Post.objects.get(slug__exact=slug)
    if request.method == 'POST':
        if request.user.is_authenticated:
            if not post.like_set.create(user = request.user).exists():
                post.like_set.create(user = request.user)
            else:
                like = request.user.like_set.get(post=post)
                like.delete()
        else:
            return redirect('login')
        return redirect(reverse('post_detail_url', kwargs={'slug':slug}))

video/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="theme-light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Главная страница {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <nav class=" navbar navbar-expand-lg bg-white sticky-top navbar-light bg-black p-3 shadow-sm">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}"><i class="fa-solid fa-shop "><strong><h2>Free<tube><b>Tube</h2></b></tube></strong></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      </button>
      <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto ">
          <div class="ms-auto d-none d-lg-block">
            <form action="{% url 'search' %}">
            <div class="input-group m-1">
              
              <input  name="search" type="text" class="form-control border-warning" style="color:#7a7a7a">
              <button type="submit"  class="btn btn-warning text-white"><b>Поиск </b></button>
            </div>
          </form>
          </div>
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link mx-2  active" aria-current="page" href="{% url 'login_site'%}"><h5><b>Войти</b></h5></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link mx-2  active" href="{% url 'logout_site'%}"><h5><b>Выход</b> </h5></a>
          </li>
          {% endif %}
          <h5 class="m-2" style="color: orange;"><b>|</b></h5>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link mx-2 active " href="http://127.0.0.1:8000/admin"><h5 class="text-danger"><b>ADMIN</b></h5></a>
          </li>
          {% endif %}
        <ul class="navbar-nav ms-auto ">
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link mx-2 active" href="{% url 'register' %}"><h5><b>Регистрация</b></h5></a>
          </li>
            {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link  active" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <h5>
                  <b>
                    Профиль
                  </b>
                </h5>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'create_post'%}"><b>Создать видео</b></a></li>
              <li><a class="dropdown-item" href="{% url 'profile' user.id %}"><b>Перейти в профиль</b></a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
      </div>
    </div>
  </nav>
    <div style="height: 1500px;">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

video/templates/category_detail.html
{% extends 'base.html' %}
{% block title %} 
 {{ category.title}}
 {% endblock %}
{% block content %}
<div class="container">
    <h1 class="line">{{category.title}}</h1>
      {% for post in category.post_set.all %}

        <div class="col">
          <section class="articles">
            <article>
              <div class="article-wrapper">
                <figure>
                  <a href="{{post.get_link}}">
                  <img src="{{post.preview.url}}" alt="" />
                </figure>
                <div class="article-body">
                  <h2>{{post.title}}</h2>
                  <p class="text-end">
                    {{post.date}}
                    <br>
                    {{post.author}}
                  </p>
                </div>
                </a>
              </div>
            </article>
          </section>
          </div>
        {% endfor %}
{% endblock %}

video/templates/create_post.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Создать видео</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href=" {% static 'media/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=" { static 'vendor/bootstrap/css/bootstrap.min.css'} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{ static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' }">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{ static 'vendor/animate/animate.css' }">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{ static 'vendor/css-hamburgers/hamburgers.min.css' }">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{ static 'vendor/select2/select2.min.css' }">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="contact1">
		<div class="container-contact1">
			<div class="contact1-pic js-tilt" data-tilt>
				<img src="https://yt3.googleusercontent.com/UlCHZn3O_XYw4ycBEYCeaOmjniIB3XLnfacdwaNXabld6t7KBAQcl_iAO3ZAcApp7e0rscFhRA=s900-c-k-c0x00ffffff-no-rj" alt="">
			</div>

			<form action="{% url 'create_post' %}" method="POST"  class="contact1-form validate-form" enctype="multipart/form-data">
				{% csrf_token %}
				<span class="contact1-form-title">
					<h3><b>Создать видео</b></h3>
				</span>

				<div class="wrap-input1 validate-input" data-validate = "Name is required">
					<input class="input1" type="text" name="title" placeholder="Название" required>
					<span class="shadow-input1"></span>
				</div>

				<label class="input-file">
                    <span class="input-file-text" type="text"><b>Видео</b></span>
                    <input type="file" name="video">        
                     <span class="input-file-btn"><b>Выбрать файл</b></span>
              </label>
<br><br>
              <label class="input-file">
                <span class="input-file-text" type="text"><b>Превью</b></span>
                <input type="file" name="preview">        
                 <span class="input-file-btn"><b>Выбрать файл</b></span>
          </label>
<br><br>
				<div class="wrap-input1 validate-input" data-validate = "Message is required">
					<textarea class="input1" name="description" placeholder="Описание"></textarea>
					<span class="shadow-input1"></span>
				</div>

				<div class="container-contact1-form-btn">
					<button class="contact1-form-btn">
						<span>
							<b>Создать</b>
							<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						</span>
					</button>
				</div>
			</form>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="{ static 'vendor/jquery/jquery-3.2.1.min.js' }"></script>
<!--===============================================================================================-->
	<script src="{ static 'vendor/bootstrap/js/popper.js' }"></script>
	<script src="{ static 'vendor/bootstrap/js/bootstrap.min.js' }"></script>
<!--===============================================================================================-->
	<script src="{ static 'vendor/select2/select2.min.js' }"></script>
<!--===============================================================================================-->
	<script src="{ static 'vendor/tilt/tilt.jquery.min.js' }"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

<!--===============================================================================================-->
	<script src="{ static 'js/main.js'}"></script>

</body>
</html>

video/templates/index.html
{% extends 'base.html' %}
{% block title %} Главая страница {% endblock %}
{% block content %}
<div class="container">
    <h1 class="line"><b>Популярные</b></h1>
    <div class="row">
    <div class="row row-cols-1 row-cols-md-5 g-3">
    {% for post in featureds %}
    <div class="col">
    <section class="articles">
      <article>
        <div class="article-wrapper">
          <figure>
            <a href="{{post.get_link}}">
            <img src="{{post.preview.url}}" alt="" />
          </figure>
          <div class="article-body">
            <h2>{{post.title}}</h2>
            <p class="text-end">
              {{post.date}}
              <br>
              {{post.author}}
            </p>
          </div>
          </a>
        </div>
      </article>
    </section>
    </div>
    {% endfor %}
  </div>
    <h1 class="line"><b>Видео</b></h1>
    <div class="row">
      <div class="row row-cols-md-3"> 
    {% for post in posts %}
    <div class="col">
      <section class="articles">
        <article>
          <div class="article-wrapper">
            <figure>
              <a href="{{post.get_link}}">
              <img src="{{post.preview.url}}" alt="" />
            </figure>
            <div class="article-body">
              <h2>{{post.title}}</h2>
              <p class="text-end">
                {{post.date}}
                <br>
                {{post.author}}
              </p>
            </div>
            </a>
          </div>
        </article>
      </section>
      </div>
    {% endfor %}
    </div>
    <nav aria-label="...">
      <ul class="pagination pagination-lg">
        <li class="page-item active" aria-current="page">
          <span class="page-link">1</span>
        </li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
      </ul>
    </nav>
  </div>
    <h1 class="line"><b>Категории</b></h1>
    <div class="row mt-3 row-cols-1 row-cols-md-5 g-4">
      {% for category in categories %}
      <div class="col">
        <div class="card cover-card">
         <a href="{{category.get_link}}">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center;">
              <a href="{{category.get_link}}">{{category.title}}</a>
            </h5>
          </div>
        </div>
      </a>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

video/templates/post_detail.html
{% extends 'base.html'%}
{% block title %} {{post.title}} {% endblock %}
{% block content %}
<div class = 'row m-4'>
  <div class="col-md-8">
    <video controls sc>
      <source src='{{post.video.url}}' type="video/mp4">
    </video>
      <h1 class="line">Комментарии</h1>
      <p class="text-end">Коментариев: {{post.comment_set.count}}</p>
      {% if request.user.is_authenticated %}
      <form action="{% url 'comment' post.slug %}" method="POST">
          {% csrf_token %}
          <textarea name="text" id="" cols="30" rows="10"></textarea> 
          <button>Отправить</button>
      </form>
      {% else %}
      <p>
          Что бы написать коментарий вы должны 
          <a href="{% url 'login_site' %}">Войти</a>
           или 
           <a href="{% url 'register' %}">Зарегистрироваться</a>
          </p>
      {% endif %}
      <div class="row row-cols-1 row-cols-md-1 g-4">
          {% for comment in post.comment_set.all %}
          <div class="col">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{comment.author.username}}</h5>
                <p class="card-text">{{comment.text}}</p>
                <p class="card-text">{{comment.date|date:'d-F-Y'}}</p>
              </div>
            </div>
          </div>
          {% endfor %}
  </div>
  </div>
  <div class="col-md-4">
      <div class="description">
            <div>
              <b class="m-4">
                {{post.title}}
              </b>
            </div>
            <div class="m-2">
           <p>
            {{post.description}}
           </p>
          </div>
      </div>
      {% if user.is_superuser or request.user == post.author %}
          <a href="{% url 'post_delete' post.slug %}">
            <button class="btn btn-danger">Удалить</button>
          </a>
          {% endif %} 
      {% if request.user == post.author %}
    <a href="{% url 'edit_post' post.slug %}">
      <button class="btn btn-primary">Изменить</button>
    </a>
      {% endif %}
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <a href="{{post.get_link}}">
            <img src="{{post.preview.url}}" class="img-fluid rounded-start" style="width: 200px; height: 155px;" alt="...">
          </a>
          </div>
          <div class="col-md-8">
            <a href="{{post.get_link}}">
            <div class="card-body">
              <h5 class="card-title"></h5>
              <p class="card-text">{{post.title}}</p>
              <p><small class="text-bode"></small></p>
            </div>
            <p class="card-text m-2"><small class="text-body-secondary">{{post.author}} {{post.date}}</small></p>
          </div>
        </a>
        </div>
      </div>
  </div>
</div>
{% endblock %}

video/templates/profile.html
{% extends 'base.html' %}
{% block title %} Профиль {% endblock %}
{% block content %}
<div class="container">
    <div class="main-body"> 
          <div class="row gutters-sm m-3">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if profile.avatar %}
                    <img src="{{profile.avatar.url}}" alt="Admin" class="rounded-circle" width="150">
                    {% else %}

                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    {% endif %}
                    <div class="mt-3">
                      <h4>{{ profile.user.username }}</h4>
                      <p class="text-secondary mb-1">{{ profile.description }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0"> Полное имя</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ profile.user.first_name}} {{profile.user.last_name}}
                    </div>
                  </div>

                  <hr>

                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email  </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{profile.user.email}}
                    </div>
                  </div>

                  <hr>

                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">День рождения</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{profile.birth_day}}
                    </div>
                  </div>
                  
                  <hr>
                  </div>
                </div>  
              </div>
            </div>
          </div>
          <p class="m-3">Видео пользователя {{profile.user.username}}: </p>
          <div class="row">
            <div class="row row-cols-md-3">
              {% for post in user.post_set.all %}
              <div class="col">
                <section class="articles">
                  <article>
                    <div class="article-wrapper">
                      <figure>
                        <a href="{{post.get_link}}">
                        <img src="{{post.preview.url}}" alt="" />
                      </figure>
                      <div class="article-body">
                        <h2>{{post.title}}</h2>
                        <p class="text-end">
                          {{post.date}}
                          <br>
                          {{post.author}}
                        </p>
                      </div>
                      </a>
                    </div>
                  </article>
                </section>
                </div>
            {% endfor %}
          </div>
          </div>
        </div>
    {% endblock %}

video/templates/search.html
{% extends 'base.html' %}
{% block title %}
  Поиск
{% endblock %}
{% block content %}
<div class="container">
  <h1 class="line">Видео</h1>
  <div class="row">
    <div class="row row-cols-md-3"> 
  {% for post in posts %}
  <div class="col">
    <section class="articles">
      <article>
        <div class="article-wrapper">
          <figure>
            <a href="{{post.get_link}}">
            <img src="{{post.preview.url}}" alt="" />
          </figure>
          <div class="article-body">
            <h2>{{post.title}}</h2>
            <p class="text-end">
              {{post.date}}
              <br>
              {{post.author}}
            </p>
          </div>
          </a>
        </div>
      </article>
    </section>
    </div>
  {% endfor %}
  </div>
    </div>
    {% endblock %}